import { memo, useEffect, useState } from 'react';
import type MermaidApi from 'mermaid';
import { Skeleton } from '@/components/ui/Skeleton';

interface MermaidDiagramProps {
  /** A Mermaid definition string, e.g. `graph LR ...`. */
  chart: string;
}

/**
 * Renders a Mermaid definition to inline SVG.
 *
 * Mermaid is heavy and only needed on this view, so it's dynamically imported
 * (its own chunk) and initialised once. The definition is generated by us from
 * the API's typed graph — never user input — so injecting the returned SVG via
 * `dangerouslySetInnerHTML` is safe; `securityLevel: 'strict'` is belt-and-braces.
 */

let mermaidPromise: Promise<typeof MermaidApi> | null = null;

const loadMermaid = (): Promise<typeof MermaidApi> => {
  if (!mermaidPromise) {
    mermaidPromise = import('mermaid').then((mod) => {
      mod.default.initialize({
        startOnLoad: false,
        theme: 'neutral',
        securityLevel: 'strict',
        flowchart: { useMaxWidth: true, htmlLabels: false, curve: 'basis' },
      });
      return mod.default;
    });
  }
  return mermaidPromise;
};

export const MermaidDiagram = memo(({ chart }: MermaidDiagramProps) => {
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setSvg(null);
    setError(null);

    const renderId = `mermaid-${Math.random().toString(36).slice(2)}`;
    loadMermaid()
      .then((mermaid) => mermaid.render(renderId, chart))
      .then((result) => {
        if (!cancelled) setSvg(result.svg);
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to render the diagram.');
        }
      });

    return () => {
      cancelled = true;
    };
  }, [chart]);

  if (error) {
    return (
      <div
        role="alert"
        className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"
      >
        <strong className="font-semibold">Diagram render failed:</strong> {error}
      </div>
    );
  }

  if (!svg) return <Skeleton className="h-[600px] w-full" />;

  return (
    <div
      className="mermaid-diagram overflow-auto [&_svg]:h-auto [&_svg]:max-w-none"
      // Safe: SVG is produced by Mermaid from a definition we generate.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
});
MermaidDiagram.displayName = 'MermaidDiagram';
